### ISSUE TITLE
Issue deploying laravel app to ionos on staging env (it was working before)

### ISSUE THREAD

**Issue by aschelch** [ionos-deploy-now/deploy-to-ionos#9]
Hi, 

When creating a new branch and trying to deploy it to a staging environment, I now have an error on stage "Deploy to IONOS".
Here is the log : 

<img width="961" alt="CleanShot 2022-11-29 at 13 39 21@2x" src="https://user-images.githubusercontent.com/2005559/204531909-d3a7dc39-c90e-4e07-b942-b13b91f2e0eb.png">

It looks like at the first deployment, it tries to run the `recurring` part.
To confirm it, I even try to comment the `pre-deployment-remote-commands:` and I then get another error 

<img width="1048" alt="CleanShot 2022-11-29 at 13 46 33@2x" src="https://user-images.githubusercontent.com/2005559/204532878-4f54d62e-16fc-45bd-9146-cc9737352f07.png">

Everything was working well until now.. And I did not change anything

My `config.yaml` looks like: 
```
version: 1.0

deploy:
  # configuration part, which is taken at the FIRST deployment of each branch
  bootstrap:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - mkdir storage/logs
      - php artisan down
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan optimize:clear
      - php artisan migrate --force -n
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

  # configuration part, which is taken at ALL FURTHER deployments of this branch
  recurring:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
    # commands that are executed at the real webspace NOT at build servers BEFORE copying new files
    pre-deployment-remote-commands:
      - php artisan down
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan optimize:clear
      - php artisan migrate --force -n
      - php artisan storage:link
      - php artisan optimize
      - php artisan up
      - php artisan queue:monitor default

# runtime:
#   cron-jobs:
    # - command: php artisan schedule:run >> /dev/null 2>&1
    #   schedule: "* * * * *"
```
